spring:
  application:
    name: route-project-sender
  kafka:
    bootstrap-servers: "localhost:9092"
    template:
      default-topic: "coordinate"
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

